SE1735-G6/OnlineMedicine/OnlineMedicine/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineMedicine.Models;
using PayPal;
using PayPal.Api;
using System.Collections.Generic;
using System.Security.Claims;

namespace OnlineMedicine.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly AppDbContext _context = new AppDbContext();

        public IActionResult AddToCart(int medicineId, int quantity, decimal unitPrice)
        {
            int accId = GetId();
            Cart c;

            if (_context.Carts.FirstOrDefault(x => x.AccountId == accId && x.MedicineId == medicineId) == null)
            {
                c = new Cart
                {
                    AccountId = accId,
                    Quantity = quantity,
                    MedicineId = medicineId,
                    Price = quantity * unitPrice
                };
                //trong cart chưa có thì add
                _context.Carts.Add(c);
                _context.SaveChanges();
            }
            else
            {
                //có rồi thì update lại thông tin
                c = _context.Carts.FirstOrDefault(x => x.AccountId == accId && x.MedicineId == medicineId);
                c.AccountId = accId;
                c.Quantity = quantity;
                c.MedicineId = medicineId;
                c.Price = quantity * unitPrice;
                _context.Carts.Update(c);
                _context.SaveChanges();
            }

            return Redirect("/Medicine/Details/" + medicineId);

        }

        public IActionResult Details(int? id)
        {
            int accId = GetId();
            List<Cart> list = _context.Carts.Include(x => x.Account).
                Include(x => x.Medicine).Include(x => x.Medicine.Type).Include(x => x.Medicine.Category).
                Include(x => x.Medicine.Country).
                Where(x => x.AccountId == accId).ToList();
            ViewBag.list = list;
            return View();
        }

        public IActionResult UpdateQuantity(int quantity, int mediId, decimal unitPrice)
        {
            int accId = GetId();

            Cart c = _context.Carts.FirstOrDefault(x => x.AccountId == accId && x.MedicineId == mediId);
            c.Quantity = quantity;
            c.Price = unitPrice * quantity;
            _context.Carts.Update(c);
            _context.SaveChanges();


            return Redirect("/Cart/Details/" + accId);
        }

        public IActionResult DeleteOneItemInCart(int id)
        {
            int accId = GetId();
            Cart c = _context.Carts.FirstOrDefault(x => x.AccountId == accId && x.MedicineId == id);
            _context.Carts.Remove(c);
            _context.SaveChanges();

            return Redirect("/Cart/Details/" + accId);

        }

        public int GetId()
        {
            var userClaims = HttpContext.User.Claims;
            var sidClaim = userClaims.FirstOrDefault(u => u.Type == ClaimTypes.Sid);
            return Convert.ToInt32(sidClaim.Value);
        }
        public IActionResult CheckOut()
        {
            
            int accountId = GetId();
            if (HttpContext.Session.GetString("listId") == null)
            {
                return Redirect("/Cart/Details/" + accountId);
            }
            var listId = HttpContext.Session.GetString("listId");
            string[] s = listId.Split('-');
            
            List<Cart> carts = _context.Carts.Where(x => x.AccountId == accountId && s.Contains(x.MedicineId.ToString())).ToList();
            Models.Order order = new Models.Order();


            decimal totalMoney = 0;
            foreach (Cart c in carts)
            {
                Medicine product = _context.Medicines.FirstOrDefault(x => x.Id == c.MedicineId);
                if (product.Quantity < c.Quantity)
                {
                    ViewBag.Error = "Some medicines are out stock.";
                    return View("List");
                }
                totalMoney += c.Price;
            }
            order.TotalMoney = totalMoney;
            order.CreatedDate = DateTime.Now;
            order.AccountId = accountId;
            order.CustomerName = HttpContext.Session.GetString("customerName");
            order.Address = HttpContext.Session.GetString("customerAddress");
            order.PhoneNumber = HttpContext.Session.GetString("customerPhoneNumber");
            _context.Orders.Add(order);
            if (_context.SaveChanges() > 0)
            {
                List<OrderDetail> listDetail = new List<OrderDetail>();
                List<Medicine> listProduct = new List<Medicine>();
                int orderId = _context.Orders.OrderBy(order => order.Id).Last().Id;
                foreach (Cart c in carts)
                {
                    OrderDetail detail = new OrderDetail();
                    detail.OrderId = orderId;
                    detail.MedicineId = c.MedicineId;
                    detail.Quantity = c.Quantity;
                    detail.Price = c.Price;
                    listDetail.Add(detail);
                    Medicine product = _context.Medicines.FirstOrDefault(x => x.Id == detail.MedicineId);
                    product.Quantity = product.Quantity - c.Quantity;
                    listProduct.Add(product);
                }
                _context.OrderDetails.AddRange(listDetail);
                _context.SaveChanges();
                _context.Medicines.UpdateRange(listProduct);
                _context.SaveChanges();

                _context.Carts.RemoveRange(carts);
                _context.SaveChanges();


            }
            ViewBag.Order = _context.Orders.Where(x => x.AccountId == order.AccountId).Include(x => x.Account).OrderBy(order => order.Id).Last();
            ViewBag.OrderDetails = _context.OrderDetails.Where(x => x.OrderId == order.Id)
                .Include(x => x.Medicine).ToList();
            HttpContext.Session.Remove("listId");
            HttpContext.Session.Remove("customerName");
            HttpContext.Session.Remove("customerAddress");
            HttpContext.Session.Remove("customerPhoneNumber");
            return View();
        }
        public IActionResult FailureView()
        {
            return View();
        }
        public IActionResult SuccessView()
        {
            return View();
        }
        public IActionResult PaypalPayment(string listId = null) {
            int accountId = GetId();
            if (string.IsNullOrEmpty(listId))
            {
                return Redirect("/Cart/Details/" + accountId);
            }

            HttpContext.Session.SetString("listId", listId);
            return RedirectToAction("CheckOutInfo");
        }
        public IActionResult CheckOutInfo(string name = null, string address = null, string phoneNumber = null)
        {
            if(name == null || address == null || phoneNumber == null)
            {
                int accountId = GetId();
                Models.Account acc = _context.Accounts.FirstOrDefault(x => x.Id == accountId);
                ViewBag.Account = acc;

                if (HttpContext.Session.GetString("listId") == null)
                {
                    return Redirect("/Cart/Details/" + accountId);
                }
                var listId = HttpContext.Session.GetString("listId");
                string[] s = listId.Split('-');

                List<Cart> carts = _context.Carts.Where(x => x.AccountId == accountId && s.Contains(x.MedicineId.ToString()))
                    .Include(x => x.Medicine)
                    .Include(x => x.Medicine.Type)
                    .Include(x => x.Medicine.Category)
                    .Include(x => x.Medicine.Country).ToList();
                ViewBag.Cart = carts;

                return View();
            }
            else
            {
                HttpContext.Session.SetString("customerName", name);
                HttpContext.Session.SetString("customerAddress", address);
                HttpContext.Session.SetString("customerPhoneNumber", phoneNumber);
                return RedirectToAction("PaymentWithPayPal");
            }

        }
        public ActionResult PaymentWithPaypal(string Cancel = null)
        {
            //getting the apiContext  
            APIContext apiContext = PaypalConfiguration.GetAPIContext();
            try
            {
                //A resource representing a Payer that funds a payment Payment Method as paypal  
                //Payer Id will be returned when payment proceeds or click to pay  
                string payerId = Request.Query["PayerID"].ToString();
                if (string.IsNullOrEmpty(payerId))
                {
                    //this section will be executed first because PayerID doesn't exist  
                    //it is returned by the create function call of the payment class  
                    // Creating a payment  
                    // baseURL is the url on which paypal sendsback the data.  
                    string baseURI = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}{HttpContext.Request.PathBase}/Cart/PaymentWithPayPal?";
                    //here we are generating guid for storing the paymentID received in session  
                    //which will be used in the payment execution  
                    var guid = Convert.ToString((new Random()).Next(100000));
                    //CreatePayment function gives us the payment approval url  
                    //on which payer is redirected for paypal account payment  
                    var createdPayment = this.CreatePayment(apiContext, baseURI + "guid=" + guid);
                    //get links returned from paypal in response to Create function call  
                    var links = createdPayment.links.GetEnumerator();
                    string paypalRedirectUrl = null;

SE1735-G6/OnlineMedicine/OnlineMedicine/Controllers/MedicineController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineMedicine.Models;
using OnlineMedicine.ViewModels;
using System;

namespace OnlineMedicine.Controllers
{
    public class MedicineController : Controller
    {
        private readonly AppDbContext _context;

        public MedicineController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Medicine
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Medicine> medicines = _context.Medicines
                                    .Include(m => m.Category)
                                    .Include(m => m.Country)
                                    .ToList();

            List<Category> categories = _context.Categories
                                        .ToList();

            MedicineListModel model = new MedicineListModel
            {
                Medicines = medicines,
                Categories = categories
            };

            return View(model);
        }

        // GET: Medicine
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(List<int>? CategoryIds, string? SearchKeyword)
        {
            if(SearchKeyword == null || SearchKeyword == string.Empty)
            {
                SearchKeyword = "";
            }
            List<Medicine> medicines = _context.Medicines
                                    .Include(m => m.Category)
                                    .Include(m => m.Country)
                                    .Where(m => CategoryIds == null || CategoryIds.Count <= 0 || CategoryIds.Contains(m.CategoryId))
                                    .Where(m => m.Name.Contains(SearchKeyword)
                                                || m.Descript.Contains(SearchKeyword)
                                                || m.Country.Name.Contains(SearchKeyword))
                                    .ToList();

            List<Category> categories = _context.Categories
                                        .ToList();

            MedicineListModel model = new MedicineListModel
            {
                CategoryIds = CategoryIds,
                Medicines = medicines,
                Categories = categories
            };

            return View(model);
        }
        public IActionResult Details(int? id)
        {
            Medicine m = _context.Medicines.Include(x => x.Country).
                            Include(x => x.Type).Include(x => x.Category).
                            FirstOrDefault(x => x.Id == id);
            ViewBag.m = m;
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult ListAll()
        {
            ViewBag.Medicine = _context.Medicines.Include(x => x.Category).Include(x => x.Type).Include(x => x.Country).ToList();
            return View("List");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.category = _context.Categories.ToList();
            ViewBag.type = _context.Types.ToList();
            ViewBag.country = _context.Countries.ToList();
            return View("Create");
        }

        [HttpPost]
        public IActionResult Create(string name, int category, DateTime expriedDate, string image, string descript, int minAge,
            int typeId, int country, int price, int quantity)
        {
            Medicine m = new Medicine();
            m.Name = name;
            m.CategoryId = category;
            m.ExpiredDate = expriedDate;
            m.Image = image;
            m.Descript = descript;
            m.MinAge = minAge;
            m.TypeId = typeId;
            m.Price = price;
            m.Quantity = quantity;
            m.CountryId = country;
            _context.Medicines.Add(m);
            if (_context.SaveChanges() > 0)
            {
                ViewBag.Medicine = _context.Medicines.Include(x => x.Category).Include(x => x.Type).Include(x => x.Country).ToList();
                return View("List");
            }
            ViewBag.Error = "Create new failed";
            return View("Create");
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int mid)
        {
            Medicine m = _context.Medicines.Include(x => x.Category)
                .Include(x => x.Type).Include(x => x.Country)
                .FirstOrDefault(x => x.Id == mid);
            ViewBag.category = _context.Categories.Where(x => x.Id != m.CategoryId).ToList();
            ViewBag.type = _context.Types.Where(x => x.Id != m.TypeId).ToList();
            ViewBag.country = _context.Countries.Where(x => x.Id != m.CountryId).ToList();
            ViewBag.date = m.ExpiredDate.Value.ToString("yyyy-MM-dd");
            ViewBag.Medicine = m;
            return View("Edit");
        }
        [HttpPost]
        public IActionResult Edit(string name, int category, DateTime expriedDate, string image, string descript, int minAge,
           int typeId, int country, decimal price, int quantity, int mid)
        {
            Medicine m = _context.Medicines.Include(x => x.Category)
                .Include(x => x.Type).Include(x => x.Country).FirstOrDefault(x => x.Id == mid);
            m.Name = name;
            m.CategoryId = category;
            m.ExpiredDate = expriedDate;
            m.Image = image;
            m.Descript = descript;
            m.MinAge = minAge;
            m.TypeId = typeId;
            m.Price = price;
            m.Quantity = quantity;
            m.CountryId = country;
            if (_context.SaveChanges() >= 0)
            {
                m = _context.Medicines.Include(x => x.Category)
               .Include(x => x.Type).Include(x => x.Country).FirstOrDefault(x => x.Id == mid);
                ViewBag.category = _context.Categories.Where(x => x.Id != m.CategoryId).ToList();
                ViewBag.type = _context.Types.Where(x => x.Id != m.TypeId).ToList();
                ViewBag.country = _context.Countries.Where(x => x.Id != m.CountryId).ToList();
                ViewBag.date = m.ExpiredDate.Value.ToString("yyyy-MM-dd");
                ViewBag.Medicine = m;
                return View("Edit");
            }
            return View("Edit");
        }
        public IActionResult Delete(int mid)
        {

            Medicine m = _context.Medicines.FirstOrDefault(x => x.Id == mid);
            m.Quantity = 0;
            if (_context.SaveChanges() >= 0)
            {
                ViewBag.Medicine = _context.Medicines.Include(x => x.Category).Include(x => x.Type).Include(x => x.Country).ToList();
                return View("List");
            }
            ViewBag.Medicine = _context.Medicines.Include(x => x.Category).Include(x => x.Type).Include(x => x.Country).ToList();
            return View("List");

        }
    }
}

SE1735-G6/OnlineMedicine/OnlineMedicine/Views/Medicine/Create.cshtml
@model OnlineMedicine.Models.Medicine

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Medicine</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <h1>@ViewBag.Error</h1>
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input type="text" required name="name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select name="category" class="form-control">
                    @foreach (Category c in ViewBag.category)
                    {
                        <option value="@c.Id" >@c.Name</option>
                    }
                    
               </select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input name="price" required type="number" class="form-control" />
                <span asp-validation-for="ExpiredDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity"required class="control-label"></label>
                <input name="quantity" required type="number" class="form-control" />
                <span asp-validation-for="ExpiredDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpiredDate" class="control-label"></label>
                <input name="expriedDate" required type="date" class="form-control" />
                <span asp-validation-for="ExpiredDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input type="text" name="image" required class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descript" class="control-label"></label>
                <input type="text" required name="descript" class="form-control" />
                <span asp-validation-for="Descript" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MinAge" class="control-label"></label>
                <input type="number" required name="minAge" class="form-control" />
                <span asp-validation-for="MinAge" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select name="typeId" class="form-control">
                    @foreach (var c in ViewBag.type)
                    {
                        <option value="@c.Id" >@c.Name</option>
                    }

                </select>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <select name="country" class="form-control">
                    @foreach (Country c in ViewBag.country)
                    {
                        <option value="@c.Id" >@c.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <br/>
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SE1735-G6/OnlineMedicine/OnlineMedicine/Views/Medicine/Delete.cshtml
@model OnlineMedicine.Models.Medicine

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Medicine</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpiredDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpiredDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descript)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descript)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MinAge)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MinAge)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SE1735-G6/OnlineMedicine/OnlineMedicine/Views/Medicine/Details.cshtml
@using OnlineMedicine.Models

@{
    Medicine m = ViewBag.m;
}
<p>
    <a style="text-decoration:none" href="/Home">Home</a> /
    <a style="text-decoration:none" href="/Medicine">Medicines List</a> /
    <span>@m.Name</span>
</p>
<h1>
</h1>
<div class="row" style="margin-top: 7%; padding: 50px 30px;border: 3px solid rgb(217, 217, 217); border-radius: 15px">
    <div class="col-4">
        <img src="@m.Image" style="max-width:372px" />
    </div>
    <div class="col-8">

        <h3>@m.Name</h3>



        <p><span style="font-weight:bold; display:inline-block;width: 100px;">Country </span> : @m.Country.Name</p>
        <p><span style="font-weight:bold; display:inline-block;width: 100px;">Description </span> : @m.Descript</p>
        <p><span style="font-weight:bold; display:inline-block;width: 100px;">Expiry </span> : @DateTime.Parse(@m.ExpiredDate.ToString()).ToString("dd-MMM-yyyy")</p>
        <p><span style="font-weight:bold; display:inline-block;width: 100px;">Min Age </span> : @m.MinAge</p>
        <p>
            <form asp-action="Index" asp-controller="Medicine" method="post">
                <input type="hidden" name="CategoryIds" value="@m.CategoryId" />
                <span style="font-weight:bold; display:inline-block;width: 100px;">Category </span>
                : <button class="btn-secondary" type="submit">
                    @m.Category.Name
                </button>
            </form>
        </p>
        <div id="cartForm">
            <form asp-controller="Cart" asp-action="AddToCart" method="post">
                <input type="hidden" name="medicineId" value="@m.Id" />
                <input type="hidden" name="unitPrice" value="@m.Price" />

                <p><span style="font-weight:bold; display:inline-block; width: 90px;">Type </span> &nbsp;&nbsp;: @m.Type.Name</p>
                <p><span style="font-weight:bold; display:inline-block; width: 90px;">Price </span> &nbsp;&nbsp;: @decimal.Round(@m.Price,2)$ /@m.Type.Name</p>

                <p><span style="font-weight:bold; display:inline-block; width: 90px;">Quantity: </span> &nbsp;&nbsp;: (The remaining amount: @m.Quantity)</p>

                Choose <input name="quantity" style="width:200px;margin-left:50px" id="quantityInput" class="btn btn-primary" type="number" value="1" min="1" max="@m.Quantity" />

                @{
                    if (!User.Identity.IsAuthenticated)
                    {
                        <br />
                        <a style="margin-top:3%;margin-left:10%" asp-controller="Account" asp-action="Login" class="btn btn-outline-primary" type="submit" disabled="@(m.Quantity == 0)">Add to Cart</a>
                    }
                    else
                    {
                        <br />
                        <button style="margin-top:3%;margin-left:10%" class="btn btn-outline-primary" type="submit" disabled="@(m.Quantity == 0)">Add to Cart</button>
                    }
                }
            </form>

        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

<script>
    document.querySelector("#cartForm form").addEventListener("submit", async function (event) {
        event.preventDefault(); // Ngăn chặn việc submit ban đầu

        const form = event.target;

        // Thực hiện kiểm tra điều kiện
        if (form.checkValidity()) {
            // Hiển thị thông báo thành công
            Swal.fire({
                icon: 'success',
                title: 'Add to Cart Successful',
                showConfirmButton: false,
                timer: 2000 // Hiển thị trong 2 giây
            });

            // Chờ 2 giây trước khi thực hiện submit form
            await new Promise(resolve => setTimeout(resolve, 2000));

            // Thực hiện submit form
            form.submit();
        } else {
            // Nếu form không hợp lệ, hiển thị thông báo lỗi
            Swal.fire({
                icon: 'error',
                title: 'Add to Cart fail',
                showConfirmButton: false,
                timer: 2000
            });
        }
    });
</script>

SE1735-G6/OnlineMedicine/OnlineMedicine/Views/Medicine/Edit.cshtml
@model OnlineMedicine.Models.Medicine

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Medicine</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
                <div class="form-group">
                    <input type="hidden" name="mid" value="@ViewBag.Medicine.Id" />
                    <label asp-for="Name" class="control-label"></label>
                    <input type="text" required name="name" value="@ViewBag.Medicine.Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Category" class="control-label"></label>
                    <select name="category" class="form-control">
                        <option value="@ViewBag.Medicine.Category.Id">@ViewBag.Medicine.Category.Name</option>
                        @foreach (Category c in ViewBag.category)
                        {
                            <option value="@c.Id">@c.Name</option>
                        }

                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input name="price" required type="number" value="@ViewBag.Medicine.Price" class="form-control" />
                    <span asp-validation-for="ExpiredDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Quantity" required class="control-label"></label>
                    <input name="quantity" required type="number" value="@ViewBag.Medicine.Quantity" class="form-control" />
                    <span asp-validation-for="ExpiredDate" class="text-danger"></span>
                </div>
          
                <div class="form-group">
                    <label asp-for="ExpiredDate" class="control-label"></label>
                    <input name="expriedDate" required value="@ViewBag.date" type="date" class="form-control" />
                    <span asp-validation-for="ExpiredDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Image" class="control-label"></label>
                    <input type="text" name="image" value="@ViewBag.Medicine.Image" required class="form-control" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Descript" class="control-label"></label>
                    <input type="text" required value="@ViewBag.Medicine.Descript" name="descript" class="form-control" />
                    <span asp-validation-for="Descript" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MinAge" class="control-label"></label>
                    <input type="number" required name="minAge" value="@ViewBag.Medicine.MinAge" class="form-control" />
                    <span asp-validation-for="MinAge" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Type" class="control-label"></label>
                    <select name="typeId" class="form-control">
                        <option value="@ViewBag.Medicine.Type.Id">@ViewBag.Medicine.Type.Name</option>
                        @foreach (var c in ViewBag.type)
                        {
                            <option value="@c.Id">@c.Name</option>
                        }

                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="Country" class="control-label"></label>
                    <select name="country" class="form-control">
                        <option value="@ViewBag.Medicine.Country.Id">@ViewBag.Medicine.Country.Name</option>
                        @foreach (Country c in ViewBag.country)
                        {
                            <option value="@c.Id">@c.Name</option>
                        }
                    </select>
                </div>
           
            
            <div class="form-group">
                <br />
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
        <a asp-action="ListAll">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}