SE1735-G6/OnlineMedicine/OnlineMedicine/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineMedicine.Models;
using PayPal;
using PayPal.Api;
using System.Collections.Generic;
using System.Security.Claims;

namespace OnlineMedicine.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly AppDbContext _context = new AppDbContext();

        public IActionResult AddToCart(int medicineId, int quantity, decimal unitPrice)
        {
            int accId = GetId();
            Cart c;

            if (_context.Carts.FirstOrDefault(x => x.AccountId == accId && x.MedicineId == medicineId) == null)
            {
                c = new Cart
                {
                    AccountId = accId,
                    Quantity = quantity,
                    MedicineId = medicineId,
                    Price = quantity * unitPrice
                };
                //trong cart chưa có thì add
                _context.Carts.Add(c);
                _context.SaveChanges();
            }
            else
            {
                //có rồi thì update lại thông tin
                c = _context.Carts.FirstOrDefault(x => x.AccountId == accId && x.MedicineId == medicineId);
                c.AccountId = accId;
                c.Quantity = quantity;
                c.MedicineId = medicineId;
                c.Price = quantity * unitPrice;
                _context.Carts.Update(c);
                _context.SaveChanges();
            }

            return Redirect("/Medicine/Details/" + medicineId);

        }

        public IActionResult Details(int? id)
        {
            int accId = GetId();
            List<Cart> list = _context.Carts.Include(x => x.Account).
                Include(x => x.Medicine).Include(x => x.Medicine.Type).Include(x => x.Medicine.Category).
                Include(x => x.Medicine.Country).
                Where(x => x.AccountId == accId).ToList();
            ViewBag.list = list;
            return View();
        }

        public IActionResult UpdateQuantity(int quantity, int mediId, decimal unitPrice)
        {
            int accId = GetId();

            Cart c = _context.Carts.FirstOrDefault(x => x.AccountId == accId && x.MedicineId == mediId);
            c.Quantity = quantity;
            c.Price = unitPrice * quantity;
            _context.Carts.Update(c);
            _context.SaveChanges();


            return Redirect("/Cart/Details/" + accId);
        }

        public IActionResult DeleteOneItemInCart(int id)
        {
            int accId = GetId();
            Cart c = _context.Carts.FirstOrDefault(x => x.AccountId == accId && x.MedicineId == id);
            _context.Carts.Remove(c);
            _context.SaveChanges();

            return Redirect("/Cart/Details/" + accId);

        }

        public int GetId()
        {
            var userClaims = HttpContext.User.Claims;
            var sidClaim = userClaims.FirstOrDefault(u => u.Type == ClaimTypes.Sid);
            return Convert.ToInt32(sidClaim.Value);
        }
        public IActionResult CheckOut()
        {
            
            int accountId = GetId();
            if (HttpContext.Session.GetString("listId") == null)
            {
                return Redirect("/Cart/Details/" + accountId);
            }
            var listId = HttpContext.Session.GetString("listId");
            string[] s = listId.Split('-');
            
            List<Cart> carts = _context.Carts.Where(x => x.AccountId == accountId && s.Contains(x.MedicineId.ToString())).ToList();
            Models.Order order = new Models.Order();


            decimal totalMoney = 0;
            foreach (Cart c in carts)
            {
                Medicine product = _context.Medicines.FirstOrDefault(x => x.Id == c.MedicineId);
                if (product.Quantity < c.Quantity)
                {
                    ViewBag.Error = "Some medicines are out stock.";
                    return View("List");
                }
                totalMoney += c.Price;
            }
            order.TotalMoney = totalMoney;
            order.CreatedDate = DateTime.Now;
            order.AccountId = accountId;
            order.CustomerName = HttpContext.Session.GetString("customerName");
            order.Address = HttpContext.Session.GetString("customerAddress");
            order.PhoneNumber = HttpContext.Session.GetString("customerPhoneNumber");
            _context.Orders.Add(order);
            if (_context.SaveChanges() > 0)
            {
                List<OrderDetail> listDetail = new List<OrderDetail>();
                List<Medicine> listProduct = new List<Medicine>();
                int orderId = _context.Orders.OrderBy(order => order.Id).Last().Id;
                foreach (Cart c in carts)
                {
                    OrderDetail detail = new OrderDetail();
                    detail.OrderId = orderId;
                    detail.MedicineId = c.MedicineId;
                    detail.Quantity = c.Quantity;
                    detail.Price = c.Price;
                    listDetail.Add(detail);
                    Medicine product = _context.Medicines.FirstOrDefault(x => x.Id == detail.MedicineId);
                    product.Quantity = product.Quantity - c.Quantity;
                    listProduct.Add(product);
                }
                _context.OrderDetails.AddRange(listDetail);
                _context.SaveChanges();
                _context.Medicines.UpdateRange(listProduct);
                _context.SaveChanges();

                _context.Carts.RemoveRange(carts);
                _context.SaveChanges();


            }
            ViewBag.Order = _context.Orders.Where(x => x.AccountId == order.AccountId).Include(x => x.Account).OrderBy(order => order.Id).Last();
            ViewBag.OrderDetails = _context.OrderDetails.Where(x => x.OrderId == order.Id)
                .Include(x => x.Medicine).ToList();
            HttpContext.Session.Remove("listId");
            HttpContext.Session.Remove("customerName");
            HttpContext.Session.Remove("customerAddress");
            HttpContext.Session.Remove("customerPhoneNumber");
            return View();
        }
        public IActionResult FailureView()
        {
            return View();
        }
        public IActionResult SuccessView()
        {
            return View();
        }
        public IActionResult PaypalPayment(string listId = null) {
            int accountId = GetId();
            if (string.IsNullOrEmpty(listId))
            {
                return Redirect("/Cart/Details/" + accountId);
            }

            HttpContext.Session.SetString("listId", listId);
            return RedirectToAction("CheckOutInfo");
        }
        public IActionResult CheckOutInfo(string name = null, string address = null, string phoneNumber = null)
        {
            if(name == null || address == null || phoneNumber == null)
            {
                int accountId = GetId();
                Models.Account acc = _context.Accounts.FirstOrDefault(x => x.Id == accountId);
                ViewBag.Account = acc;

                if (HttpContext.Session.GetString("listId") == null)
                {
                    return Redirect("/Cart/Details/" + accountId);
                }
                var listId = HttpContext.Session.GetString("listId");
                string[] s = listId.Split('-');

                List<Cart> carts = _context.Carts.Where(x => x.AccountId == accountId && s.Contains(x.MedicineId.ToString()))
                    .Include(x => x.Medicine)
                    .Include(x => x.Medicine.Type)
                    .Include(x => x.Medicine.Category)
                    .Include(x => x.Medicine.Country).ToList();
                ViewBag.Cart = carts;

                return View();
            }
            else
            {
                HttpContext.Session.SetString("customerName", name);
                HttpContext.Session.SetString("customerAddress", address);
                HttpContext.Session.SetString("customerPhoneNumber", phoneNumber);
                return RedirectToAction("PaymentWithPayPal");
            }

        }
        public ActionResult PaymentWithPaypal(string Cancel = null)
        {
            //getting the apiContext  
            APIContext apiContext = PaypalConfiguration.GetAPIContext();
            try
            {
                //A resource representing a Payer that funds a payment Payment Method as paypal  
                //Payer Id will be returned when payment proceeds or click to pay  
                string payerId = Request.Query["PayerID"].ToString();
                if (string.IsNullOrEmpty(payerId))
                {
                    //this section will be executed first because PayerID doesn't exist  
                    //it is returned by the create function call of the payment class  
                    // Creating a payment  
                    // baseURL is the url on which paypal sendsback the data.  
                    string baseURI = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}{HttpContext.Request.PathBase}/Cart/PaymentWithPayPal?";
                    //here we are generating guid for storing the paymentID received in session  
                    //which will be used in the payment execution  
                    var guid = Convert.ToString((new Random()).Next(100000));
                    //CreatePayment function gives us the payment approval url  
                    //on which payer is redirected for paypal account payment  
                    var createdPayment = this.CreatePayment(apiContext, baseURI + "guid=" + guid);
                    //get links returned from paypal in response to Create function call  
                    var links = createdPayment.links.GetEnumerator();
                    string paypalRedirectUrl = null;

SE1735-G6/OnlineMedicine/OnlineMedicine/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineMedicine.Models;
using System.Security.Claims;
using System.Security.Principal;


namespace OnlineShopMedicine.Controllers
{

    public class OrderController : Controller
    {
        private readonly AppDbContext _context;
        public int GetId()
        {
            var userClaims = HttpContext.User.Claims;
            var sidClaim = userClaims.FirstOrDefault(u => u.Type == ClaimTypes.Sid);
            if (sidClaim == null)
            {
                return 0;
            }
            return Convert.ToInt32(sidClaim.Value);
        }
        public OrderController()
        {
            _context = new AppDbContext();
        }
        public IActionResult Index()
        {
            int n = GetId();
            Account account = _context.Accounts.Include(x => x.Role).FirstOrDefault(u => u.Id == n);
            if (account == null)
            {
                return RedirectToAction("Login", "Account");
            }
            List<Order> orders = new List<Order>();
            orders = _context.Orders.Where(x => x.AccountId == account.Id).Include(x => x.Account).ToList();
            ViewBag.Orders = orders;
            return View("Index");
        }

        [HttpGet]
        public IActionResult Search(DateTime fromDate, DateTime toDate, int sort)
        {
            int n = GetId();
            Account account = _context.Accounts.Include(x => x.Role).FirstOrDefault(u => u.Id == n);
            if (account == null)
            {
                return RedirectToAction("Login", "Account");
            }
            List<Order> orders = new List<Order>();
            orders = _context.Orders.Where(x => x.AccountId == account.Id)
            .Include(x => x.Account).ToList();
            if (fromDate.Year >= 2000)
            {
                orders = orders.Where(x => x.AccountId == account.Id && fromDate.CompareTo(x.CreatedDate) <= 0).ToList();
                ViewBag.from = fromDate.ToString("yyyy-MM-dd");
            }
            if (toDate.Year >= 2000)
            {
                orders = orders.Where(x => x.AccountId == account.Id && toDate.CompareTo(x.CreatedDate) >= 0).ToList();
                ViewBag.to = toDate.ToString("yyyy-MM-dd");
            }
            if (sort == 1)
            {
                orders = orders.OrderByDescending(x => x.CreatedDate).ToList();
            }
            if (sort == 2)
            {
                orders = orders.OrderBy(x => x.CreatedDate).ToList();
            }
            ViewBag.Sort = sort;
            ViewBag.Orders = orders;
            return View("Index");
        }

        public IActionResult ListOrderByAdmin()
        {
            List<Order> orders = new List<Order>();
            orders = _context.Orders.Include(x => x.Account).OrderByDescending(x => x.CreatedDate).ToList();
            ViewBag.Orders = orders;
            return View("OrderList");
        }

        [HttpPost]
        public IActionResult Filter(DateTime fromDate, DateTime toDate, int sort)
        {
            List<Order> orders = new List<Order>();
            orders = _context.Orders.Include(x => x.Account).OrderByDescending(x => x.CreatedDate).ToList();
            if (fromDate.Year >= 2000)
            {
                orders = orders.Where(x => fromDate.CompareTo(x.CreatedDate) <= 0).ToList();
                ViewBag.from = fromDate.ToString("yyyy-MM-dd");
            }
            if (toDate.Year >= 2000)
            {
                orders = orders.Where(x => toDate.CompareTo(x.CreatedDate) >= 0).ToList();
                ViewBag.to = toDate.ToString("yyyy-MM-dd");
            }
            if (sort == 1)
            {
                orders = orders.OrderByDescending(x => x.CreatedDate).ToList();
            }
            if (sort == 2)
            {
                orders = orders.OrderBy(x => x.CreatedDate).ToList();
            }
            ViewBag.Sort = sort;
            ViewBag.Orders = orders;
            return View("OrderList");
        }
    }
}

SE1735-G6/OnlineMedicine/OnlineMedicine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineMedicine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineMedicine.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img style="width: 120px; height: 70px" src="https://i.ibb.co/pQQBjHp/logo-clean.png" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicine" asp-action="Index">Medicines List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    @{
                        if (!User.Identity.IsAuthenticated)
                        {
                            <ul class="navbar-nav flex-grow-2">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                            </ul>
                        }
                        else
                        {
                            <ul class="navbar-nav flex-grow-2">
                                @if (User.IsInRole("Admin"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Medicine" asp-action="ListAll">Manage Medicine</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="ListOrderByAdmin">View Orders</a>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Details">
                                            Cart <i class="fa fa-shopping-cart" style="color: #0074e4;"></i>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                                    </li>
                                }
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Edit">Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogOut">Logout</a>
                                </li>
                            </ul>
                        }
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineMedicine - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>